### ISSUE TITLE
What is the license for this project (and `syncing-server-js`)?

### ISSUE THREAD

**Issue by kthchew** [standardnotes/standalone#13]
It seems that neither this repo nor [`syncing-server-js`](https://github.com/standardnotes/syncing-server-js) have a clear license (e.g. indicated by a LICENSE file). Technically, this likely means [we have no permission at all to use/modify this code](https://choosealicense.com/no-permission/), though this seems like an oversight.

I see most of the other repos by Standard Notes are under the AGPL-3.0 license (such as `web`, `desktop`, etc.). For clarification, is the same meant to apply for both `standalone` and `syncing-server-js` as well?

**Comment by JaspalSuri** [comment]
Hi @kthchew, thank you for bringing this issue to our attention. We'll look into it and update the repos accordingly!
