### ISSUE TITLE
what I can use myself redis and mysql

### ISSUE THREAD

**Issue by dislazy** [standardnotes/standalone#16]
Service Versions (please complete the following information):

- syncing-server-js: latest
- auth: latest
- api-gateway: latest

**Comment by JaspalSuri** [comment]
I'm not sure I understand the question. Are you trying to decide between Redis and MySQL?

**Comment by dislazy** [comment]
I want to use mysql and redis instances set up in the cloud

**Comment by dislazy** [comment]
> I'm not sure I understand the question. Are you trying to decide between Redis and MySQL?

I want to use mysql and redis instances set up in the cloud

**Comment by mobitar** [comment]
You should be able to just by setting up the values in your .env to the remote values of your DB and Redis instance.

**Comment by dislazy** [comment]
> You should be able to just by setting up the values in your .env to the remote values of your DB and Redis instance.

ok thank you

**Comment by karolsojko** [comment]
Closing this as it was resolved.

@dislazy also please keep in mind to not use the `latest` tag on application version since the version that are in the docker-compose file are the ones that are compatible with each other. If you use change the versions to `latest` - that might cause unexpected problems.

**Comment by retmas-gh** [comment]
Hello,
I am not sure that alone will suffice or I am doing something wrong myself - you can of course change the values in .env, but the checks to wait for db:3306 are, as far as I am aware, hardcoded with no way to change them without changing the docker images.
Hosting an external database i obviously commented the db part in compose yaml. Can I do anything here or am I doomed to run two databases?
Kind regards.
