### ISSUE TITLE
Maintain a "current-compatible" tag on dockerhub

### ISSUE THREAD

**Issue by eric-pierce** [standardnotes/standalone#20]
**Describe the issue**
Currently the "latest" tag on dockerhub can cause compatibility issues with the various microservices, and the only place that the compatible versions are maintained is on the standalone docker-compose file.

By also maintaining a "current-compatible" tag across microservices on dockerhub users will always pull just the services which work with each other for infrastructures which aren't able to leverage the standalone scripts.

**Comment by JaspalSuri** [comment]
Hi @eric-pierce, thanks for that suggestion and insight. I'll pass this along to the dev team for review. 🙂

**Comment by karolsojko** [comment]
Not sure if I'm getting the purpose of this @eric-pierce - could you elaborate more on this?

The "current-compatible" versions are the version in `standalone`. Anything that is earlier than what we have in the standalone is not production or self-hosting ready and as such should not be used in conjunction with other services.

**Comment by eric-pierce** [comment]
Thanks for the response @karolsojko, I understand that by using the standalone scripts the compatible services and their version numbers are auto-deployed. This ask is about enabling an alternative way of identifying the version numbers which are considered production ready (the same versions in the standalone docker-compose file) via tags on dockerhub (ie https://hub.docker.com/r/standardnotes/syncing-server-js/tags?page=1&ordering=last_updated).

The reason for this ask is that while the standalone scripts do a wonderful job of automating environment variable configuration, container pulls, and more, not all infrastructure setups lend themselves to having scripts maintain their own docker-compose files.

Similar to the "stable" tag on the web container, this would provide a simple way of identifying (and pulling/updating) the containers which are compatible with each other from dockerhub.

Thanks again, and for all that you and the SN team have built.

**Comment by karolsojko** [comment]
`latest` is the tag that is production ready, but there is no way of us guaranteeing your self defined services will be compatible with each other.

Example 1:
Let's say your `syncing-server-js` service updates to the latest image version based on usage of the `latest` tag.
In that same setup `auth` service will stay behind on a version that is not compatible with that `latest` version of `syncing-server-js`

Example 2:
`syncing-server-js` service updates to the latest image version based on usage of the `latest` tag and is now depenedent upon a new service that we defined and your setup is lacking.

Of course you are welcome to experiment but keep in mind we won't be able to help solve potential issues/errors on a self defined service grid.

**Comment by eric-pierce** [comment]
Thanks @karolsojko - I think that the additional tag would help with example 1, but not 2 (which I hadn't considered), and the main added benefit would be ensuring that software is up to date when not using the standalone script approach.

In example 1 above, the "current-compatible" tag would be applied to the last compatible build of syncing-server-js (probably the build before "latest"), and would also be applied to the last compatible build of the auth service (which I believe would also be tagged with "latest" in this example)

In example 2, where you're adding a new micro-service you're absolutely right, this solution wouldn't help and the new service would need to be added by the infrastructure owner in order to maintain a working system.

**Comment by Ryonez** [comment]
> the new service would need to be added by the infrastructure owner in order to maintain a working system.

As far as I knew one the major points of docker is that everything is in a container and is easy to manage. Sure, there is setups where some services are split out and containers are talking to each other, like using a reverse proxy to secure a web service, or databases that serve content for other dockers

The latest changes have are apparently worse than I though if you also expect a script you make to *manage* everything as well. The old container was perfect, though I would've been happy for it to use an external database and redis as an *option*. Ideally, it'd be able to function completely on it's own.

These recent changes have kinda screwed me and the setup I use over. My os (unRaid), doesn't support docker-compose. I'm also not happy having a script managing containers outside of the one the os already uses. So where the old container that was available was usable because it had everything in one container that I could manage, it's now been split out into 6 new containers I'd need to set up (I already maintain database containers). My notes are now unable to sync, and there's no solutions that are feasible for setup currently.

I've requested [linuxserver.io](https://discourse.linuxserver.io/t/request-standards-new-sync-service/3109) to look into making an AIO container again. I still have not been able to figure out why everything has been split out into such a mess.

Standard Notes for me went from something amazing to something I cannot rely on until there's a feasible solution I can use.

**Comment by eric-pierce** [comment]
@Ryonez this isn't an ideal solution, but it should be possible to set up the relevant docker containers without relying on the scripts or docker compose, though I do imagine it'll take to some time to get the configuration setup right. In case it is helpful, I've set up the services without using the standalone scripts using docker-compose, you should be able to convert those container settings to standard docker run commands (effectively the opposite of what this website https://www.composerize.com/ offers).

I've parameterized the "compatible" service numbers in my env file and unfortunately will need to manually update them from time to time as they are updated in the standalone repo, but this will at least enable a working (and hopefully stable) system.

My relevant docker-compose services: https://pastebin.com/pWjJsEh7
My entire docker-compose in case you want to see it, this includes redis and the db service as well: https://github.com/eric-pierce/Personal-Cloud/blob/main/docker-compose.yml

**Comment by Ryonez** [comment]
> I do imagine it'll take to some time

From the looks of things, quite a long time. I do thank you for your documentation, it's always good to have different ways people have set something up.

Unfortunately maintaining 6 separate containers, 5 not counting redis, is still rather overwhelming and would be a maintenance nightmare. The auth container has 31 env values, all of which I'd be entering manually. And the same values are used across several containers. Entrypoints aren't supported as part of the template so those would have to become extra parameters on my system (unRaid).

This separation of components has been the most frustrating thing I've experienced with Standard Notes. I can understand *adding* redis support. Why is redis a requirement though? There's no technical reason why it couldn't work without it, it has done so before. That isn't to say there is no benefit for redis, there certainly is especially with a larger number of users. But this new requirement causes a failure point to exist.
I also don't understand the benefit of separating out all the components of the sync service out. None of it seems designed to work on their own, all components are needed. What is the point to the separate containers, it makes maintaining it 5 times as hard. Why bother with docker at all at this point?

All up my opinion comes to:
* Requiring redis externally is a bad move, not every environment is going to be large enough to make use of it.
* Separating 1 service into 5 components is a bad move.
* The script is unusable for me.

These first two points above are the cause of a broken ecosystem for this service with me. They are each a breaking change requiring a fair amount of time and effort to adjust to, though that could be better or worse depending on the system as admin has.

My position on each of the three points is:
* Redis, I don't really want it at the moment. It's mostly for my own use, and I'd have to research redis to make sure to set it up for more than one service to be able to use it. I really don't want this right now, not as something I have to manage. A container image with it built in would be better right now if a requirement is to be forced.
* This... it's a nightmare. 31 env flags to set, custom docker run commands. This is a huge turn off, I want to manage 1 service, not 5 components.
* My system has things in certain places, so it won't help me. By the way, it checks for docker but assumes the system will have docker-compose. That shouldn't be an assumption.

I am sorry if I do sounds upset, cause I kinda am. The app on my computer and phone has updated, and the sync service I have is no longer compatible. and has been been for quite some time now. And don't understand why this is such a horrible mess. If someone could explain why the changes where made, I'd really appreciate that.

**Comment by Joshndroid** [comment]
Dammit. I was looking at this as a notes app and had a look through docker-hub with everything depricated. One quick look at the docker-compose and a myriad of containers would need to be installed to manage it (whether it be within portainer or unraid). While i get portainer can handled the script its a punish when trying to further tie in with reverse proxies and the like, with unraid its a straight up nightmare of multiple containers just for 1 service. :( I echo your comments @Ryonez and I havnt even had the chance to set it up once, let alone have it working prior till the change.

**Comment by mobitar** [comment]
@Ryonez I do understand the frustration. If I was a self-hoster relying on the old setup and now all of a sudden was faced with taking on a part time devops job just to keep up, I'd be disappointed too. The truth is that when looking to design our ecosystem, we have to consider our use case first, and self-hosting second. If it were the other way around, we'd end up with an infrastructure that is perfectly suited for 1 user, but not for the potential of many million users. So, we have to take a "scale-first" approach, because we are building the product to be able to serve a large quantity of users.

The reason for containerization in general is that each service has different scaling requirements. For example, /sync gets hit much harder than /auth, so would need 10x the amount of containers. Whereas if it were all just one service, we couldn't have that granular scaling approach, and we'd have to indiscriminately scale the entire ecosystem every time we needed to handle more load.

I'm not quite sure there is ever a possibility of going back now, but my hope is that any wrinkles in the self-hosting process that have emerged as part of this migration will be ironed out in the short term, so that at the very least the documentation you read should match 1:1 with the end result, and no further hiccups arise.

**Comment by Ryonez** [comment]
Thank you for the explanation on the splitting out of components @mobitar. Well, services I guess.

I'd mentioned this to some friends and they were guessing scaling was behind the split. 

I do wish to see progress, and I understand the benefits to scaling. I don't think reverting the work would be a feasible solution at all either. Rather, would it be possible for you to consider building another container image that would act as an all in one container for server owners with less knowledge and experience like myself? That would allow coverage or larger organizations as well as smaller homedevs and server owners.

mysql wouldn't be need I'd expect, databases are fairly common requirements for many things, and personally I feel I have that sorted. Redis could be another left out I guess. It's not common, and it would be something I'd have to learn. But it has potential benefits for other services once set up. Would like to see something that use an external redis, but fall back on it's own if one isn't available though. That would add flexibility for people. And then the biggest part is the 5 separate services required for sync itself.

I will try and have a look at this again, and see if I can find a solution that'll work to a degree without requiring me to enter 150 odd env variables to my templates on the os. And maybe learn a little redis.

**Comment by mobitar** [comment]
To be honest the goal of the Docker script is to make deployment as seamless as possible. I'd say if the script works out of the box for you, which should be the majority usecase, then self-hosting the new server is a dream and way easier than the old one. However as with things like these not everyone gets the out-of-box experience, and the perception is thus that the new setup is much more difficult. In any case even things like Redis should be abstracted so that you don't have to think about it or do anything special. It will run the Redis node in your Docker setup, so you don't need to set it up separately.

**Comment by Ryonez** [comment]
The script will attempt to run, as it only checks for docker. However, the lack of docker-compose, and the fact my filesystem is laid out differently, a specific service manages docker and docker is managed through that service, the script will not be safe to run.

Besides, if I have to set up redis, I might as well set it up to be usable for multiple services. I don't want to have a large amount of docker containers to handle when most have to be handled manually, nor would I run 10+ database containers when one can serve all of them as it was designed to. I don't have one large AIO script or compose file I can use. For reference, this is the docker documentation for my OS: https://wiki.unraid.net/Manual/Docker_Management

In this cause you have an entire os that is no longer "supported" with your containers. It's not just one user, anyone using this OS will encounter some rather hefty difficulties with the changes. Hence the request for a docker container that'll function as an AIO.

Docker is completely usable. The use of compose is not something I have available unfortunately.

**Comment by Ryonez** [comment]
This one line, was responsible for running sync before:
```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='alteria-standardnotes-sync' --net='docker-secure' --cpuset-cpus='4,1,5' -e TZ="Pacific/Auckland" -e HOST_OS="Unraid" -e 'DISABLE_USER_REGISTRATION'='true' -e 'DB_POOL_SIZE'='30' -e 'DB_WAIT_TIMEOUT'='180' -e 'DISABLE_USER_REGISTRATION'='false' -e 'DATADOG_ENABLED'='false' -e 'EXPOSED_PORT'='3000' -e 'RAILS_ENV'='production' -e 'DB_USERNAME'='standardnotes-sync' -e 'SECRET_KEY_BASE'='XXX' -e 'RAILS_ENV'='production' -e 'DB_HOST'='alteria-mariadb' -e 'DB_PORT'='3306' -e 'DB_DATABASE'='standardnotes-sync' -e 'DB_PASSWORD'='XXX' -e 'RAILS_LOG_TO_STDOUT'='true' -v '/mnt/user/appdata/alteria-standardnotes/':'/backups':'rw' 'standardnotes/syncing-server:stable' 
```

That command was made from this page:
![image](https://user-images.githubusercontent.com/16157130/127783340-70f1265e-1162-46ad-8a1c-a1b6adb52b34.png)
![image](https://user-images.githubusercontent.com/16157130/127783460-e35bc2f8-ca44-4359-b104-6fd0db904ea8.png)
![image](https://user-images.githubusercontent.com/16157130/127783467-3274ed40-260c-4d3b-b3dc-3299b7e2c1c5.png)


>  then self-hosting the new server is a dream and way easier than the old one.

Nope, this has been a joke of an experience. It failed to import the data, which is now lost as I dropped the database before noticing the sqldump file was empty (thankfully exported my note clientside already), I'm getting `"level":"debug","message":"Response error: TokenExpiredError: jwt expired\`, I've spend over 3 hours picking this mess apart and it's still not going.
We really need an AIO that does deal with this mess.

![image](https://user-images.githubusercontent.com/16157130/127786597-ff5d1383-4145-4b0a-af58-43ad8466fa92.png)

I feel like I'm at the point were I'm going to be forced to find another note app, which I really don't want. But this isn't working, and it's now far to complex to really self host on this os if this is going to be the new hosting experience.

**Comment by Joshndroid** [comment]
@Ryonez as this simply wouldn't work I had to move to Joplin for unraid

**Comment by eric-pierce** [comment]
@karolsojko with the latest change to remove version specific docker image pulls, this issue/ask appears to have essentially been implemented. Would you agree? If so, I'll close. Thank you!

**Comment by karolsojko** [comment]
@eric-pierce yes, we've changed the way we release to a [trunk based development](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development) - so every change we apply is PROD ready and self-hosting ready. You can update your self hosted server at any time to get the latest changes :)

**Comment by eric-pierce** [comment]
Thanks @karolsojko, I'll close this as complete then!
