### ISSUE TITLE
[BUG] Services are publicly accessible

### ISSUE THREAD

**Issue by tobiaskarch** [standardnotes/standalone#22]
**Describe the bug**
Hi, I just updated my self-hosted Standard Notes from syncing-server to standalone using the [official docs](https://docs.standardnotes.org/self-hosting/docker/). 
After that I noticed that the services api-gateway, mysql and redis are publicly accessible.

`$ docker ps` (server): Containers are bound to 0.0.0.0

`$ nmap <server-ip> -p 49165` (from your machine, 49165 was the port assigned to MySQL): 
```
PORT      STATE SERVICE
49165/tcp open  unknown
```

**To Reproduce**
1. Follow the [docker setup guide](https://docs.standardnotes.org/self-hosting/docker/)
2. Check which ports are used by the mentioned services: `$ docker ps`
3. Open `http://<server-ip>:3000` in browser / connect to MySQL and Redis from your computer

**Expected behavior**
- A reverse proxy is necessary to access the api-gateway as described in [the guide](https://docs.standardnotes.org/self-hosting/docker/#securing-your-server)
- It's not possible to connect to MySQL and Redis from outside the server

**Actual behavior**
- api-gateway can be accessed via `http://<server-ip>:3000` in the browser
- It's possible to connect to MySQL and Redis from outside

**Service Versions**
I use the latest version of this repository: https://github.com/standardnotes/standalone/commit/88decddc6ebe01e0cc61e2208ea2bc873629d353

**Suggested solution**
Add `127.0.0.1::` to the ports in the docker-compose.yml file. For example `3306` -> `127.0.0.1::3306`

**Comment by karolsojko** [comment]
Hi @tobiaskarch 

thanks for reporting this.

So the way our services are setup is that the `api-gateway` service IS the proxy/gateway to access our services. There is no other way to call any other underlying service then by going through `api-gateway`. So naturally API Gateway has to be exposed to internet access - all other services are inaccessible directly. 

Note: given many variations of how people utilize this infrastructure, keep in mind not every setup will use a reverse proxy like nginx.

As for the MySQL and Redis part - ports to those services are dynamically assigned from the host machine pool by Docker. You would have to intentionally open up port 3000, MySQL's container port and Redis container port to be accessible from you host machine in order for those services to be accessible via internet. In general it's a bad practice to open up all ports for inbound traffic (see for example AWS EC2 Security Groups - by default all inbound ports are closed).

Having that said it is not necesarilly a bad option to be able to access the MySQL container and Redis container from localhost's CLI point of view for data maintenance/backup etc.

**Comment by tobiaskarch** [comment]
Hi @karolsojko,

about the api-gateway: yes, makes sense when you consider that not everyone uses a reverse proxy.

To the other part: I use ufw which blocks all incoming connections by default. But Docker manipulates iptables, making it possible to connect to the containers from outside anyway, even though it is blocked in ufw. This behavior of Docker is not known to most people. Additionally, not everyone has the option to set up a "cloud firewall", as not every hoster offers it.

In my case, I had a firewall set up and did not open up the ports for MySQL and Redis. But they were still unintentionally opened up. For Redis it is especially bad, because it is not password protected by default.

Thus, I still suggest to bind MySQL and Redis to 127.0.0.1. Maintenance/backup is still possible with `$ docker exec`. If users want to access their database remotely, they should opt-in into that.
Alternatively, I would suggest writing an info/warning message in the docs that informs about it and how to disable it.

**Comment by karolsojko** [comment]
Sounds good @tobiaskarch - feel free to open up a pull request with this change

**Comment by eugenechae** [comment]
How about using `expose:` instead of `ports:` and skip publishing them to the host machine altogether? Added benefit of not conflicting with `mysql` or `redis` already running on the same host.

**Comment by tobiaskarch** [comment]
@eugenechae I like your idea. I will use `expose` in my PR
