### ISSUE TITLE
How to delete users on self hosted server

### ISSUE THREAD

**Issue by PhoneMechanic** [standardnotes/standalone#27]
How do I delete users from my self hosted standalone instance?

**Comment by mobitar** [comment]
You'll have to use a MySQL client to do so. There is no management dashboard presently.

**Comment by PhoneMechanic** [comment]
On the old syncing server I used the Rails console, is this still possible on the new syncing server js?

**Comment by PhoneMechanic** [comment]
> You'll have to use a MySQL client to do so. There is no management dashboard presently.
Is deleting the email in users sufficient? Or do I need to delete something else?

**Comment by mobitar** [comment]
If you want to be thorough you'd delete the User record, all Items belonging to that user uuid, all Revisions, and all Sessions.
