### ISSUE TITLE
Internal Server Error ECONNREFUSED on selfhosted instance

### ISSUE THREAD

**Issue by tim-kilian** [standardnotes/standalone#3]
Hej,

I am trying to set up a sync server instance. I've got it to work so far, but I have trubble to keep it stable. I am getting such errors in my logs, and do not understand why they happen. Maybe you've got a clue what might be wrong. Maybe I am missing some env variables. 

```
Error: Internal Server Error
    at Request.callback (/var/www/node_modules/superagent/lib/node/index.js:883:15)
    at IncomingMessage.<anonymous> (/var/www/node_modules/superagent/lib/node/index.js:1127:20)
    at IncomingMessage.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

```

And this one is also very strange, as it comes from the syncing server and get a connection refused from itself? I replaced the IP with the `sync` keyword. 

```
Error: connect ECONNREFUSED sync:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)
```

It is also really strange, because it sometimes work. Here is a screenshot, to show what I mean.

![Screenshot from 2021-05-21 13-41-22](https://user-images.githubusercontent.com/5788010/119131942-6036b680-ba3a-11eb-8efb-5c93bd17c038.png)

I also can only loggin from my self hosted web instance, but not from the desktop client or the mobile client.

## Versions
- standardnotes/api-gateway:1.4.4
- standardnotes/auth:1.6.4
- standardnotes/syncing-server-js:1.26.11

**Comment by tim-kilian** [comment]
Somehow, I got it running on all my devices. I included the env "NEW_RELIC_ENABLED=false" and I could login into my desktop and mobile clients after a fresh restart of the backend. It did not worked flawlessly, I had to retry the request  until it worked. It does not feel stable for me. I have to retry my 'sync' request about 3-5 times until it sync my data. See the screenshot above.

**Comment by karolsojko** [comment]
Hi @tim-kilian ,

sorry to hear about your experience. We've moved to a new setup and are eager to fix any issue that users are experiencing.

As for the issue that you are experiencing - my suspicion is that the `auth` services is not up/responsive as probably `syncing-server-js` is trying to make a request to it.

any chance you could stop your services and start them again and supply us with the logs of the services starting up?

**Comment by karolsojko** [comment]
We've also updated the services to latest versions so you could try if `./server.sh update` works for you

**Comment by tim-kilian** [comment]
It seems to be related to the api-gateway. I tried to change the ports to 80, because there was an IP of the Node logged in the output, and I thought it could not resolve the DNS entry.

```
sn-auth (10.245.46.182:80) open
sn-auth:80 is up - executing command
sn-sync (10.245.197.206:80) open
sn-sync:80 is up - executing command
Starting Web...
yarn run v1.22.5
$ node dist/bin/server.js
{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"sn-api-756c7c449f-bmzcp","pid":31,"time":"2021-05-31T22:30:37.832Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}
routes: 
  - controller: RevisionsController
    endpoints: 
      - route: GET /v1/items/:item_id/revisions/
      - route: GET /v1/items/:item_id/revisions/:id
  - controller: ActionsController
    endpoints: 
      - route: POST /v1/login
      - route: GET /v1/login-params
      - route: POST /v1/logout
      - route: GET /v1/auth/methods
  - controller: UsersController
    endpoints: 
      - route: PATCH /v1/users/:userId
      - route: PUT /v1/users/:userId/password
      - route: GET /v1/users/:userId/params
      - route: POST /v1/users/
      - route: PUT /v1/users/:userUuid/settings
      - route: DELETE /v1/users/:userUuid/settings/:settingName
  - controller: SessionsController
    endpoints: 
      - route: GET /v1/sessions/
      - route: DELETE /v1/sessions/:uuid
      - route: DELETE /v1/sessions/
      - route: POST /v1/sessions/refresh
  - controller: HealthCheckController
    endpoints: 
      - route: GET /healthcheck/
  - controller: LegacyController
    endpoints: 
      - route: ALL *
Error: connect ECONNREFUSED 10.245.197.206:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)
Error: Internal Server Error
    at Request.callback (/var/www/node_modules/superagent/lib/node/index.js:883:15)
    at IncomingMessage.<anonymous> (/var/www/node_modules/superagent/lib/node/index.js:1127:20)
    at IncomingMessage.emit (node:events:390:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
```

## Versions

I also updated my versions to the following:

- standardnotes/api-gateway:1.6.0
- standardnotes/auth:1.7.5
- standardnotes/syncing-server-js:1.27.4

**Comment by karolsojko** [comment]
@tim-kilian can you try `./server.sh update` to see if the latest version fixes the issue? Keep in mind you might have to update your .env files.

If not please supply us with the full output of logs when the setup starts up (in a separate file) - would be easier to track what happened.

**Comment by tim-kilian** [comment]
Seems to be even worse. But here is a new error message from the api-gateway.

```
node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at new NodeError (node:internal/errors:329:5)
    at ServerResponse.writeHead (node:_http_server:279:11)
    at ServerResponse._implicitHeader (node:_http_server:270:8)
    at write_ (node:_http_outgoing:746:9)
    at ServerResponse.end (node:_http_outgoing:835:5)
    at ServerResponse.send (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/response.js:221:10)
    at AuthMiddleware.<anonymous> (/var/www/dist/src/Controller/AuthMiddleware.js:73:47)
    at Generator.throw (<anonymous>)
    at rejected (/var/www/dist/src/Controller/AuthMiddleware.js:18:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by karolsojko** [comment]
@tim-kilian I'm pretty sure you didn't run `./server.sh update` looking at the versions of services you have. 

Look at the [docker-compose.yml](https://github.com/standardnotes/standalone/blob/main/docker-compose.yml) file, it currently has: 
- standardnotes/api-gateway:1.14.0
- standardnotes/auth:1.8.2
- standardnotes/syncing-server-js:1.34.0

**Comment by tim-kilian** [comment]
Oh, sry I wrote the wrong version number for auth. It is indeed 1.8.2.

**Comment by karolsojko** [comment]
Updated api-gateway with the latest version (your fix) in here: https://github.com/standardnotes/standalone/commit/3e9533f3d97de8c7f8978c6b3e136ddbc75cd352

can you run `./server.sh update` and check what the logs output ?

**Comment by tim-kilian** [comment]
I missed a place with the same code. Kind of the same error message, but now in HttpService instead of AuthMiddleware.

```
RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
    at new NodeError (node:internal/errors:329:5)
    at ServerResponse.writeHead (node:_http_server:279:11)
    at ServerResponse._implicitHeader (node:_http_server:270:8)
    at write_ (node:_http_outgoing:746:9)
    at ServerResponse.end (node:_http_outgoing:835:5)
    at ServerResponse.send (/var/www/node_modules/inversify-express-utils/node_modules/express/lib/response.js:221:10)
    at HttpService.<anonymous> (/var/www/dist/src/Service/HttpService.js:87:47)
    at Generator.throw (<anonymous>)
    at rejected (/var/www/dist/src/Service/HttpService.js:18:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by karolsojko** [comment]
> I missed a place with the same code. Kind of the same error message, but now in HttpService instead of AuthMiddleware.

Will add a fix.

> Also shouldn't a fix be in third place of the version number?

It's a bit more complex. We're using git-flow so when we're doing a hotfix we're bumping the last number, whenever a PR is merged from community it first has to be tested on develop and then we have to make a release with the second number bumbed.

**Comment by karolsojko** [comment]
@tim-kilian updated once again

**Comment by tim-kilian** [comment]
Hej.
the erros disappeared after updating to the latest version. I still had an error in my service configuration tho, but now it works fine. 
Thanks for the help!
