### ISSUE TITLE
Bold editor not working in iOS app

### ISSUE THREAD

**Issue by garth-xmr** [standardnotes/standalone#40]
I self host SN. The plain text editor works fine on both iOS and Mac desktop. But if I switch to the Bold editor it gives me a 404 error on mobile, while on desktop it works fine. Any ideas?

Thanks
garth

**Comment by JaspalSuri** [comment]
Hi @garth-xmr, are you loading in the extensions via your Extended code or are you hosting the extensions as well?

**Comment by garth-xmr** [comment]
Hello and thanks. How do I know if I am loaded extensions via extended code verses hosting? Thanks

**Comment by JaspalSuri** [comment]
Oh, you would have known if you recall explicitly setting the up that way, so it's safe to assume that you used the Extended Code to obtain access to our Extensions repository. 

Are you using a VPN or some sort of firewall-equivalent that might prevent the editors from loading on to your phone? If you reinstall the Bold Editor via the Extensions menu on the desktop app, does it still work?

**Comment by garth-xmr** [comment]
Fixed. Code from website was entered wrong. I "Deleted repository" and reentered my code correctly.

**Comment by JaspalSuri** [comment]
I'm sorry to hear that, but I'm glad that you were able to figure it out. Thank you for taking the time to share what went wrong; I'll pass this along as feedback for the dev team to review in order to help other users potentially avoid this situation.
