### ISSUE TITLE
How to disable new user registration

### ISSUE THREAD

**Issue by MaxVRAM** [standardnotes/standalone#42]
I've deployed as new Docker stack with the script and following the guide provided.
Using the webapp at `app.standardnotes.org` I can successfully create new users and sync notes.

But I'd now like to prevent new user registration.

After I registered my user, I tried:
1. Stopping standalone containers and and removing all the containers in the stack.
2. Setting `DISABLE_USER_REGISTRATION=true` in the `.env` file.
3. Spooling up the stack again.
4. Logged into my existing account via `app.standardnotes.org` -> no problems.
5. Logged out
5. Registered a new user - it worked :( so created a test note to see if it was actually syncing with my server.
6. Logged out
7. Logged back in using the newly created user - it worked, and had sync'd the test note as a fully functioning user :( 

Note: I couldn't find that variable documented anywhere, but after digging through some of the issues here, someone suggested setting that variable to `false` that was having issues registering, so figured it might help in the opposite case.

Is this environment variable meant to provide the functionality I'm after?
Is there some other way to disable new user registration?

Thanks!

**Comment by MaxVRAM** [comment]
Hi @karolsojko  - thanks for the help. Unfortunately I already have `DISABLE_USER_REGISTRATION=true` set in my `.env`, and I am still able to make new users.

Here's my full `.env` file:

```
LOG_LEVEL=info
NODE_ENV=development
VERSION=local

AUTH_JWT_SECRET=super_secret

EXPOSED_PORT=7020
DISABLE_USER_REGISTRATION=true
DB_HOST=db
DB_REPLICA_HOST=db
DB_PORT=3306
DB_USERNAME=std_notes_user
DB_PASSWORD=super_secret
DB_DATABASE=standard_notes_db
DB_DEBUG_LEVEL=all # "all" | "query" | "schema" | "error" | "warn" | "info" | "log" | "migration"
DB_MIGRATIONS_PATH=dist/migrations/*.js

REDIS_URL=redis://cache

#SNS_TOPIC_ARN=
#SNS_AWS_REGION=
#SQS_QUEUE_URL=
#SQS_AWS_REGION=
#S3_AWS_REGION=
#S3_BACKUP_BUCKET_NAME=

REDIS_EVENTS_CHANNEL=events

AUTH_SERVER_URL=http://auth:3000

EMAIL_ATTACHMENT_MAX_BYTE_SIZE=10485760

REVISIONS_FREQUENCY=300

# (Optional) New Relic Setup
#NEW_RELIC_ENABLED=false
#NEW_RELIC_APP_NAME="Syncing Server JS"
#NEW_RELIC_LICENSE_KEY=
#NEW_RELIC_NO_CONFIG_FILE=true
#NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=false
#NEW_RELIC_LOG_ENABLED=false
#NEW_RELIC_LOG_LEVEL=info
```

**Comment by karolsojko** [comment]
@MaxVRAM the `.env` file is responsible for the `syncing-server-js` service environment. What you want to edit is the `docker/auth.env` file - which is responsible for the `auth` service environment - that's where all user related context is processed, such as registration.

**Comment by MaxVRAM** [comment]
That certainly did the trick. Appreciate you guiding me to the right spot. I missed the part in your docs where it splits into the docker auth.env part.
