### ISSUE TITLE
Install on Raspberry 3B+ without Docker

### ISSUE THREAD

**Issue by LoneDev6** [standardnotes/standalone#48]
Hello!
Is there any way to run this on a Raspberry 3B+ without Docker?

Thanks everyone

**Comment by mobitar** [comment]
I don't believe there will be a way to run this without Docker. Why is no Docker a requirement for your use case?

**Comment by LoneDev6** [comment]
Thanks for the answer.
Currently I encountered some issues installing Docker on my Raspberry 3B+, I may have to do a clean install.

Have a nice day!
