### ISSUE TITLE
[BUG] server.sh incompatible with compose v2

### ISSUE THREAD

**Issue by kushfest** [standardnotes/standalone#57]
**Describe the bug**
The server.sh script is no longer compatible with the recently released docker compose v2, which has changed the syntax for commands from docker-compose to docker compose. 

**To Reproduce**
1. Update to compose v2
2. Attempt to run a command with server.sh
3. See the error:  ```docker-compose: command not found```

**Expected behavior**
It would be ideal, and potentially not too complicated, if the script detected the version of compose installed and adapted the command accordingly.

**Comment by karolsojko** [comment]
the `docker-compose` command was deprecated for some time and is no longer supported so we switched to the `docker compose` command in the latest update. Should be fixed with: https://github.com/standardnotes/standalone/commit/b23b61ecd146db51c5f065d23cfc47138b478ef6
