### ISSUE TITLE
server.sh install script is missing variable to properly start [BUG] ...

### ISSUE THREAD

**Issue by usshauler** [standardnotes/standalone#60]
Just going to leave this quick fix here for the Dev team. When inspecting server.sh file to initiate the docker-compose.yml file, I kept getting errors stating "unknown shorthand flag: 'd' in -d

Turns out there was a missing hyphen in the very first docker compose line.

![image](https://user-images.githubusercontent.com/49539369/150851907-df7b8900-5d83-414c-bfbc-46c975318b62.png)

I hope this helps someone else and hopefully this fix gets implemented quickly, thanks.

**Comment by moughxyz** [comment]
I believe docker-compose is deprecated in favor of `docker compose`. Maybe your docker version is outdated.

**Comment by usshauler** [comment]
My docker version is running the most current version for me which is 20.10.12. I believe this issue is more related to the fact that the script will not launch for me unless I made this change. I am running this on the latest Proxmox VE 7 and on Turnkey Core with all updates and upgrades performed.

**Comment by e-zk** [comment]
Same issue on Ubuntu 20.04, stable docker (I think), all packages are up-to-date.

```console
$ docker --version
Docker version 20.10.12, build e91ed57
$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
```
