### ISSUE TITLE
Unable to Start "docker-compose: not found"

### ISSUE THREAD

**Issue by ImaginaryResources** [standardnotes/standalone#68]
**Describe the issue**
Following the guide from [here](https://docs.standardnotes.com/self-hosting/docker/) I get the following error when I do `./server.sh start`

`./server.sh: 54: ./server.sh: docker-compose: not found` I do see the docker-compose.yml file in the same directory

**Additional Information**
Running in a LCX container with Proxmox

**Comment by HoshinoTouko** [comment]
Make sure that you have installed Docker Compose ()[https://docs.docker.com/compose/install/] and try to use the command `docker compose`.

**Comment by ImaginaryResources** [comment]
Since it's been awhile, I started a new container and it worked. Thank you!
