### ISSUE TITLE
[BUG] Cant Upload Files

### ISSUE THREAD

**Issue by Whitei520** [standardnotes/standalone#73]
```
Container                             Repository                        Tag                 Image Id            Size
------------------------------------------------------------------------------------------------------------
api-gateway-standalone                standardnotes/api-gateway         1.40.1              614ea1d3f64c        851MB
auth-standalone                       standardnotes/auth                1.46.2              6648d9486d27        928MB
auth-worker-standalone                standardnotes/auth                1.46.2              6648d9486d27        928MB
cache-standalone                      redis                             6.0-alpine          09401fed2a42        24.7MB
db-standalone                         mysql                             5.6                 dd3b2a5dcb48        303MB
files-standalone                      standardnotes/files               1.9.0               baa6121a09d1        1.05GB
syncing-server-js-standalone          standardnotes/syncing-server-js   1.54.1              2455980ced7d        973MB
syncing-server-js-worker-standalone   standardnotes/syncing-server-js   1.54.1              2455980ced7d        973MB
```

**Describe the bug**
Error when uploading attachments or files.

<img width="256" alt="Screenshot 2022-06-10 172230" src="https://user-images.githubusercontent.com/22915581/173118455-5c9e46bd-64cd-443c-8200-4b641f806fc6.png">

**To Reproduce**
1. Upload a file

**Logs**
```
Request URL: https://files-notes.REDACTED.com/v1/files/upload/create-session
Request Method: OPTIONS
Status Code: 204 
```

```
Request URL: https://files-notes.REDACTED.com/v1/files/upload/create-session
Request Method: POST
Status Code: 400 
```

<img width="392" alt="Screenshot 2022-06-10 182226" src="https://user-images.githubusercontent.com/22915581/173118909-85c5049c-02bc-456d-bb53-2db9ba035edc.png">

**Additional context**
In its current state the docker compose file doesn't account for setting a files url at all so I changed
`FILES_SERVER_URL: 'http://localhost:${EXPOSED_FILES_PORT}'`
to
`FILES_SERVER_URL: '${FILES_SERVER_URL}'`

Then added
`FILES_SERVER_URL=https://files-notes.REDACTED.com`
to the .env file.

This resulted with the correct domain showing up in the network tab of developer tools:
`{"filesServerUrl":"https://files-notes.REDACTED.com"}`

**Comment by eric-pierce** [comment]
@Whitei520 according to this comment https://github.com/standardnotes/standalone/issues/69#issuecomment-1134711428 file uploads aren't supported on the standalone/self hosted infrastructure yet.

**Comment by Whitei520** [comment]
> @Whitei520 according to [#69 (comment)](https://github.com/standardnotes/standalone/issues/69#issuecomment-1134711428) file uploads aren't supported on the standalone/self hosted infrastructure yet.

Support has just been added.
<img width="686" alt="Screenshot 2022-06-10 191252" src="https://user-images.githubusercontent.com/22915581/173126145-3dff65bb-91a9-4b1c-8560-b17e39d76e83.png">

**Comment by techmechanic1** [comment]
I'm still unable to upload files after this update...
![image](https://user-images.githubusercontent.com/79721538/173683400-510cb032-2605-4039-ad3c-7bf9d5b0ab55.png)

**Comment by karolsojko** [comment]
@techmechanic1 did you set up the `FILES_SERVER_URL`  value in your .env file and restarted the services?

anything you are seeing in logs for `docker compose logs -f files` ?

**Comment by Whitei520** [comment]
This was closed but I still have the issue. My troubleshooting steps was not the solution, it was merely my steps to try and fix part of the problem. Even after getting the correct "filesServerUrl" showing up in the network logs I still get the same upload error.

**Comment by karolsojko** [comment]
@Whitei520 could you send the output of `docker-compose logs -f files` and docker-compose logs -f auth` so I could see what's the potential error ? 

also anything in the response body of that 400 call ?

**Comment by techmechanic1** [comment]
Here is the output of docker-compose logs -f files...

```Attaching to files-standalone
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | waiting for db:3306...
files-standalone            | db (172.18.0.2:3306) open
files-standalone            | db:3306 is up - executing command
files-standalone            | cache (172.18.0.4:6379) open
files-standalone            | cache:6379 is up - executing command
files-standalone            | Starting Web...
files-standalone            | yarn run v1.22.15
files-standalone            | $ node dist/bin/server.js
files-standalone            | {"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"568ddd4a2a1c","pid":88,"time":"2022-06-14T20:20:12.502Z","msg":"Unable to find configuration file. If a configuration file is desired (common for non-containerized environments), a base configuration file can be copied from /var/www/node_modules/newrelic/newrelic.js and renamed to \"newrelic.js\" in the directory from which you will start your application. Attempting to start agent using environment variables."}
files-standalone            | {"message":"Server started on port 3000","level":"info"}```

The Files storage quota is showing 0 B of 0 B used... 

![image](https://user-images.githubusercontent.com/79721538/173829687-25721035-4a4d-4c2f-a697-3713f7366101.png)

**Comment by karolsojko** [comment]
@techmechanic1 did you create a subscription for yourself? https://docs.standardnotes.com/self-hosting/subscriptions

**Comment by Whitei520** [comment]
> @Whitei520 could you send the output of `docker compose logs -f files` and `docker compose logs -f auth` so I could see what's the potential error ?
> 
> also anything in the response body of that 400 call ?

Thanks for reopening. I checked the docker logs and found that the container did not have file permissions in the /data folder, I fixed that and now I can upload files without any errors. However I can't view or download any uploaded files. I get a 400 error in the network console with a response of "File download requires range header to be set."

```
Request URL: https://files-notes.example.com/v1/files
Request Method: GET
Status Code: 400 
Remote Address: 104.21.12.84:443
Referrer Policy: strict-origin-when-cross-origin
access-control-allow-origin: *
access-control-expose-headers: Content-Range,Accept-Ranges
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
cf-cache-status: DYNAMIC
cf-ray: 71bb5541bcf571db-LHR
content-length: 46
content-security-policy: default-src https: 'self';base-uri 'self';child-src * blob:;connect-src *;font-src * 'self';form-action 'self';frame-ancestors * *.standardnotes.org *.standardnotes.com;frame-src * blob:;img-src 'self' * data:;manifest-src 'self';media-src 'self';object-src 'self';script-src 'self';style-src 'self'
content-type: text/plain; charset=utf-8
date: Wed, 15 Jun 2022 12:33:14 GMT
etag: W/"2e-5Dp512EBepCWZARNQm+8AgbWacM"
expect-ct: max-age=0
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
referrer-policy: no-referrer
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=BH2U2bkXN5Mr%2Fm29ihibeQBDO3e9vsz7AzD"}],"group":"cf-nel","max_age":604800}
server: cloudflare
strict-transport-security: max-age=15552000; includeSubDomains
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-files-version: local
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-xss-protection: 0
:authority: files-notes.example.com
:method: GET
:path: /v1/files
:scheme: https
accept: */*
accept-encoding: identity
accept-language: en-GB,en-US;q=0.9,en;q=0.8,la;q=0.7
content-type: application/json
origin: https://notes.example.com
range: bytes=0-
referer: https://notes.example.com/
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102", "Google Chrome";v="102"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
x-application-version: Web-3.20.2
x-chunk-size: 135865
x-snjs-version: 2.114.12
x-valet-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVXVpZCI6IjRhY2ZkMTQxLTVhOWQtNDB...
```

As an extra troubleshooting step I also disabled Cloudflare proxy but the same error showed up.

**Comment by techmechanic1** [comment]
Thanks for that! @rofra 

I changed the permissions and changed the FILES_SERVER_URL and it works...I'm hosting the files on the same server but using localhost doesn't work anyway...

**Comment by rofra** [comment]
@techmechanic1:Another clarification for the file upload, if you want to implement "Storage Quota", you could simply add an entry (per user) to set the quota.
Here is an example for 10 Gigas (into bytes):
```sql
INSERT INTO subscription_settings(uuid, name, value, created_at, updated_at, user_subscription_uuid) VALUES (UUID(), "FILE_UPLOAD_BYTES_LIMIT", 10*10737418240, FLOOR(UNIX_TIMESTAMP(NOW(6))*1000000), FLOOR(UNIX_TIMESTAMP(NOW(6))*1000000), (SELECT us.uuid FROM user_subscriptions us INNER JOIN users u ON us.user_uuid=u.uuid WHERE u.email="my@email.com"));
```

StandardNote Team, could you add the cleaner one to the official documentation ?

**Comment by Smallbox012** [comment]
Hello,

I tried `FILES_SERVER_URL=http://my.public.ip.address:3125 ` in `.env` file. Then start the server, the upload/download act smoothly. 

However, when I use nginx to redirect the file server port, the upload/download functionality could not works. I set `FILES_SERVER_URL=https://my.domain/files `, then set 
`location /files {
    proxy_pass http://127.0.0.1:3125;
  }` in my nginx config file standard-notes.conf. 

I don't know whether my nginx's config is wrong, or I am supposed to setup a http public-facing file server address? Since files are end-to-end encrypted, it is safe for me to just use the http file server address in `.env` without ssl secure traffic?

**Comment by Whitei520** [comment]
Okay, well I finally found the problem I was having with "File download requires range header to be set." error.
It turns out Cloudflare for unknown reasons does not pass the "Accept-Ranges" header through its proxy. I did find a forum post though that solved the problem for me: [here](https://community.cloudflare.com/t/accept-ranges-and-content-length-headers-not-forwarded-by-cloudflare/41445/4)

After adding this line to my nginx config everything is now fixed. This doesn't explain why it still wasn't working with Cloudflare disabled but I will leave that conundrum for someone else to solve. :)
`proxy_cache off; # Required by cloudflare to pass 'Accept-Ranges' header`

I would strongly suggest this be added to the self hosted documentation for other people who use nginx and Cloudflare.

**Comment by karolsojko** [comment]
Added everything mentioned in here to [docs](https://docs.standardnotes.com/self-hosting/file-uploads) with this: https://github.com/standardnotes/docs/commit/642df79eef9dcb4bd2ff1376edec126b2bcfe31f

Thanks everyone for the input, hope it solves the issue :)

**Comment by rofra** [comment]
There is an error in the doumentationc, 1073741824 bytes shoud be 1Gb instead of 10G.

In my original SQL Request, I put _10*10737418240_ which was correct for 10G.

**Comment by karolsojko** [comment]
good catch @rofra - fixed in [here](https://github.com/standardnotes/docs/commit/8585c0aefa3bb51f4df804e9a0d953b8ccaced78)

**Comment by Nicicalu** [comment]
> Accept-Ranges

Where did you put this?

**Comment by karolsojko** [comment]
@BobWs can you make sure auth and files have the same value on `VALET_TOKEN_SECRET` ?

**Comment by BobWs** [comment]
> @BobWs can you make sure auth and files have the same value on `VALET_TOKEN_SECRET` ?

@karolsojko They are the same. They are both pulling the key from the `.env file`

**Comment by karolsojko** [comment]
@BobWs seems like you are missing the valet token in your request: https://github.com/standardnotes/files/blob/develop/src/Controller/ValetTokenAuthMiddleware.ts#L36 

Do you have the latest version of the client application? Could you see what is sent in the request to files server - the valet token should be sent either in headers or in request parameters: https://github.com/standardnotes/files/blob/develop/src/Controller/ValetTokenAuthMiddleware.ts#L19

**Comment by BobWs** [comment]
> Do you have the latest version of the client application? Could you see what is sent in the request to files server - the valet token should be sent either in headers or in request parameters: https://github.com/standardnotes/files/blob/develop/src/Controller/ValetTokenAuthMiddleware.ts#L19

Yes I have the latest MacOS desktop client version 3.22.17.
_"Could you see what is sent in the request to files server - the valet token should be sent either in headers or in request parameters"_ 
How do or where can I check this?

`FILES_SERVER_URL=http://192.168.178.100:3125` is set to the IP of the host (my Synology NAS where Docker is running) is this good?

**Comment by BobWs** [comment]
After re-checking everything and recreated the containers I now get this in the error log
```
     

db (172.18.0.10:3306) open

db:3306 is up - executing command

cache (172.18.0.3:6379) open

cache:6379 is up - executing command

Starting Web...

yarn run v1.22.15

$ node dist/bin/server.js

{"v":0,"level":30,"name":"newrelic_bootstrap","hostname":"standardnotes-files","pid":30,"time":"2022-06-28T11:46:13.712Z","msg":"NEW_RELIC_NO_CONFIG_FILE set, deferring to environment variables."}

{"message":"Server started on port 3000","level":"info"}

{"message":"Could not create upload session for resource: 7447c434-ae0f-4581-b8ee-cad8c632518e - EACCES: permission denied, mkdir '/volume1'","level":"error"}
```
I don't know why it is showing permission denied, I have set the permission to 1001:1001 as mention above, I also tried to set it to root but still no go.

What am I doing wrong?

**Comment by BobWs** [comment]
Solved it!!
The problems was that I had set `FILE_UPLOAD_PATH=/volume1/docker-data/standardnotes/uploads` instead of `FILE_UPLOAD_PATH=standardnotes/uploads` Also the `VALET_TOKEN_TTL=7200` was missing from the `auth.env file` (don't know if that was really necessary) but after changing all this it works and I can upload files.

Only problem I see is that I'm not able to preview the file/attachments via the mobile apps (iOS). I can upload files with the mobile apps but can't preview them I'm getting this error: 
![Screenshot 2022-06-28 at 14 34 38](https://user-images.githubusercontent.com/5485820/176179917-1cb8433a-8f87-47d3-96a0-a6248fb368b4.png)

**Comment by navjotjsingh** [comment]
Whenever I try to use the SQL query to add file quota to a user, I keep getting the error.

`ERROR 1242 (21000): Subquery returns more than 1 row`

**Comment by jonwsoto** [comment]
Hmm can't figure this out. 

so when you go to your FILES_SERVER_URL by typing it straight into the browser you should be getting something similar to this right?

https://filesafe.standardnotes.org


when I paste my custom URL I get 
Cannot GET /

and under developer tools you see

example.mydomain.com/:1          Failed to load resource: the server responded with a status of 404 ()


any clue??

**Comment by karolsojko** [comment]
> so when you go to your FILES_SERVER_URL by typing it straight into the browser you should be getting something similar to this right?

Files service is a different service than filesafe. Filesafe is a deprecated service. The FILES_SERVER_URL should be pointing to the file service you have running. 

> so for some reason still says no subcription despite me updating the database and all the other features working.

Did you follow these steps: https://docs.standardnotes.com/self-hosting/subscriptions

Can you also verify if the record is in the database and the auth service is connected precisely to that database ?

**Comment by jonwsoto** [comment]
I reviewed everything I did and I realized in your script for adding subscriptions this 

subscription_type=\"regular\";' \

was missing from the examples given by the other users in this chat. I added “regular” value to the row and now it works!!

**Comment by BobWs** [comment]
> subscription_type="regular";' \

Just curious, where did you edit this? 
Can you elaborate a bit more so that other people will know what to do in case of problems.
TIA

**Comment by jonwsoto** [comment]
Under the server.sh file you can see the lines of code that handle the database modifications to add subscriptions. 



    $DOCKER_COMPOSE_COMMAND exec db sh -c "MYSQL_PWD=\$MYSQL_ROOT_PASSWORD mysql \$MYSQL_DATABASE -e \
      'INSERT INTO user_roles (role_uuid , user_uuid) VALUES ((SELECT uuid FROM roles WHERE name=\"PRO_USER\" ORDER BY version DESC limit 1) ,(SELECT uuid FROM users WHERE email=\"$EMAIL\")) ON DUPLICATE KEY UPDATE role_uuid = VALUES(role_uuid);' \
    "

    $DOCKER_COMPOSE_COMMAND exec db sh -c "MYSQL_PWD=\$MYSQL_ROOT_PASSWORD mysql \$MYSQL_DATABASE -e \
      'INSERT INTO user_subscriptions SET uuid=UUID(), plan_name=\"PRO_PLAN\", ends_at=8640000000000000, created_at=0, updated_at=0, user_uuid=(SELECT uuid FROM users WHERE email=\"$EMAIL\"), subscription_id=1, subscription_type=\"regular\";' \
    "

Instead of running the script I just used phpmyadmin to modify the database manually. In the second command I was missing the subscription_type.

**Comment by BobWs** [comment]
> Under the server.sh file you can see the lines of code that handle the database modifications to add subscriptions.

Thanks for sharing!

I followed the instructions for the pro plan from here: https://github.com/standardnotes/standalone/issues/64 and I see now that `subscription_type="regular";' \ ` was missing in the instructions.

So do I need to do this all over for all my users or is there a easier way to get it done. For example how do I accomplish this with phpmyadmin?
TIA

**Comment by karolsojko** [comment]
> So do I need to do this all over for all my users or is there a easier way to get it done. For example how do I accomplish this with phpmyadmin? TIA

```sql
UPDATE user_subscriptions SET subscription_type="regular";
```
