### ISSUE TITLE
Trying to migrate from old self-hosted setup

### ISSUE THREAD

**Issue by LendingMemo** [standardnotes/standalone#9]
Hi I installed Standard Notes self hosted syncing server a while back that launches with the docker-compose up -d command. I'm trying to move it over to this new repo, and I'm failing. I seem to get the new repo up and running, but it isn't connecting to my old database. Is there something I need to do on my end?

Thanks,
Simon

**Comment by karolsojko** [comment]
Hey @LendingMemo - we've added some docs for that, can you check and try if this works for you: https://docs.standardnotes.org/self-hosting/legacy-migration/ ?

**Comment by LendingMemo** [comment]
When using command 

`sudo docker exec your_db_container_id sh -c 'exec mysqldump your_database_name -uroot -p "your_password"' > ./dbdump.sql` 

I'm getting an error: 

`Enter password: mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: NO) when trying to connect`

I have a password for my MySQL root user. Does this need to be included somehow in the command?

**Comment by LendingMemo** [comment]
I also tried with the second External Database method, and this is my result:

`mysqldump: Got error: 1045: "Access denied for user 'std_notes_user'@'localhost' (using password: YES)" when trying to connect`

**Comment by LendingMemo** [comment]
Ok I got the database dumped via the External Database method by removing the space after `-p`. For some reason it didn't like that space (I'm on Debian).
And then I successfully got the new `standalone` to install and start.
